// Expo config plugin: add `use_modular_headers!` to the iOS Podfile.
//
// @react-native-google-signin/google-signin pulls in Firebase's AppCheckCore /
// GoogleUtilities / RecaptchaInterop, which don't define modules. When built as
// static libraries (the Expo default) CocoaPods can't import them from Swift
// unless modular headers are enabled, so `pod install` fails with:
//
//   The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and
//   `RecaptchaInterop`, which do not define modules.
//
// The Podfile is regenerated by `expo prebuild`, so a manual edit doesn't
// survive. This plugin re-applies the directive on every prebuild.
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

module.exports = function withModularHeaders(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");
      if (!contents.includes("use_modular_headers!")) {
        // Insert right after the first `target '...' do` line.
        contents = contents.replace(
          /(target ['"][^'"]+['"] do\n)/,
          "$1  use_modular_headers!\n",
        );
        fs.writeFileSync(podfile, contents);
      }
      return cfg;
    },
  ]);
};
