/**
 * Deterministic mock of the backend AI endpoint (POST /api/ai) for E2E runs.
 *
 * E2E builds are exported with EXPO_PUBLIC_BACKEND_URL pointing here and a
 * fake backend session token (set by the onboarding E2E skip), so the app's
 * "free tier" provider talks to this server instead of the real Gemini proxy.
 *
 * The scripted model speaks the app's JSON tool protocol:
 *   - Asked about medications → emits a get_medications tool call, then
 *     summarizes the real tool result (scraped from fake-mychart on-device)
 *     in its respond text. This exercises the full loop: model → scraper →
 *     model → UI, with zero nondeterminism.
 *   - Chat title requests → a fixed title.
 *   - Memory build/refresh requests → a minimal valid memory JSON.
 *   - Fact extraction requests → an empty array.
 *   - Anything else → a deterministic echo via the respond tool.
 *
 * Run with: bun expo-app/e2e/mock-ai-server.ts  (PORT env, default 4600)
 */

type ChatMessage = { role: "user" | "assistant"; content: string };
type AiRequest = { messages: ChatMessage[]; system?: string; model?: string };

const PORT = Number(process.env.PORT ?? 4600);

function respondTool(text: string): string {
  return JSON.stringify({ tool: "respond", args: { text } });
}

/** Pull medication names out of a get_medications tool result blob. */
function extractMedicationNames(toolResult: string): string[] {
  const names = new Set<string>();
  // Matches "name": "Lisinopril 10mg tablet" (and patientFriendlyName text).
  for (const m of toolResult.matchAll(/"name"\s*:\s*"([^"]+)"/g)) {
    const value = m[1].trim();
    // Skip provider/recipient-style entries (heuristic: meds entries sit
    // close to dose/refill fields, but a simple length filter is enough
    // for the Homer fixture and keeps this deterministic).
    if (value && value.length < 80) names.add(value);
  }
  return [...names];
}

function scriptedMemoryJson(): string {
  return JSON.stringify({
    summary_md:
      "## Demographics\nE2E test patient digest (generated by the mock AI server).",
    facts: [
      { category: "test", text: "Memory digest generated during E2E run", source: "mychart" },
    ],
    insights: [
      {
        title: "E2E mock insight",
        body_md: "This insight is scripted by the mock AI server for E2E runs.",
        severity: "info",
        suggested_question: null,
        source_refs: ["e2e"],
      },
    ],
  });
}

function completeChat(req: AiRequest): string {
  const system = req.system ?? "";
  const lastUser = [...req.messages].reverse().find((m) => m.role === "user");
  const lastUserText = lastUser?.content ?? "";

  // Side-channel calls the app makes with their own system prompts:
  if (system.includes("You name chat conversations")) {
    return "Medication Questions";
  }
  if (system.includes("careful health-records analyst")) {
    return scriptedMemoryJson();
  }
  if (system.includes("Output ONLY a JSON array")) {
    return "[]"; // fact extractor: nothing new
  }

  // Main chat protocol.
  const toolResultMatch = lastUserText.match(
    /Tool result for get_medications:\n([\s\S]*)/,
  );
  if (toolResultMatch) {
    const meds = extractMedicationNames(toolResultMatch[1]);
    const list = meds.length > 0 ? meds.join(", ") : "no medications found";
    return respondTool(`Your current medications are: ${list}.`);
  }

  if (/medication/i.test(lastUserText)) {
    return JSON.stringify({ tool: "get_medications", args: {} });
  }

  // Deterministic fallback so any flow can assert on its own echo.
  const preview = lastUserText.slice(0, 120).replace(/\s+/g, " ").trim();
  return respondTool(`E2E mock response: ${preview}`);
}

const server = Bun.serve({
  port: PORT,
  async fetch(request) {
    const url = new URL(request.url);
    const cors = {
      "Access-Control-Allow-Origin": request.headers.get("origin") ?? "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    };

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: cors });
    }

    if (url.pathname === "/health") {
      return Response.json({ status: "ok" }, { headers: cors });
    }

    if (url.pathname === "/api/ai") {
      const auth = request.headers.get("authorization") ?? "";
      if (!auth.startsWith("Bearer ")) {
        return Response.json({ error: "unauthorized" }, { status: 401, headers: cors });
      }

      if (request.method === "GET") {
        return Response.json(
          {
            spentCents: 123,
            limitCents: 5000,
            remainingCents: 4877,
            period: "2026-06",
          },
          { headers: cors },
        );
      }

      if (request.method === "POST") {
        const body = (await request.json()) as AiRequest;
        const content = completeChat(body);
        console.log(
          `[mock-ai] ${body.messages.length} msg(s) → ${content.slice(0, 100)}`,
        );
        return Response.json({ content }, { headers: cors });
      }
    }

    return Response.json({ error: "not found" }, { status: 404, headers: cors });
  },
});

console.log(`[mock-ai] listening on http://localhost:${server.port}`);
